namespace AIArena.Wpf.Models;

public sealed record TranscriptMessage(
    int Turn,
    string Speaker,
    string SpeakerId,
    double CreatedAt,
    string Model,
    int LatencyMs,
    int PromptTokens,
    int CompletionTokens,
    int TotalTokens,
    string Status,
    string VoiceStyle,
    bool Pinned,
    string Kind,
    string Text,
    string Reasoning,
    string InternetRequester,
    string InternetTool,
    string InternetQuery,
    string InternetUrl,
    string InternetReason,
    string InternetSummary,
    string InternetCheckedAt,
    bool InternetCached,
    IReadOnlyList<string> InternetSources,
    double TokensPerSecond = 0,
    int TimeToFirstTokenMs = 0,
    string ProviderResponseId = "",
    int ModelLoadTimeMs = 0);
