using AIArena.Core.Models;
using AIArena.Core.Persistence;
using AIArena.Core.Providers;
using AIArena.Core.Services;
using AIArena.Wpf;
using AIArena.Wpf.Controls;
using AIArena.Wpf.Models;
using AIArena.Wpf.Services;
using System.Collections;
using System.Runtime.ExceptionServices;
using System.Resources;
using System.Text.Json;
using System.Threading;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;


internal static partial class Program
{
    private static int Main(string[] args)
    {
if (args.Length == 2 && args[0].Equals("--control-plane-owner-fixture", StringComparison.Ordinal))
{
    return RunControlPlaneOwnerFixture(args[1]);
}

if (args.Length == 1 && args[0].Equals("--shared-popup-theme-fixture", StringComparison.Ordinal))
{
    return RunSharedPopupThemeFixture();
}

var tests = new List<(string Name, Action Test)>
{
    ("saves and reloads visual generation settings", SaveReloadVisualGenerationSettings),
    ("agent workspace defaults on and persists its settings toggle", AgentWorkspaceDefaultsOnAndPersistsSettingsToggle),
    ("agent workspace resolves canonical model settings and tone", AgentWorkspaceResolvesCanonicalModelSettingsAndTone),
    ("normalizes system theme and blank settings", NormalizeSystemThemeAndBlankSettings),
    ("voice narration settings and text cleanup stay stable", VoiceNarrationSettingsAndTextCleanupStayStable),
    ("app shutdown survives cleanup failures", AppShutdownSurvivesCleanupFailures),
    ("main window shutdown reclose is deferred", MainWindowShutdownRecloseIsDeferred),
    ("voice narration dispose wins delayed start", VoiceNarrationDisposeWinsDelayedStart),
    ("voice narration disposal drains an in-flight start", VoiceNarrationDisposalDrainsInFlightStart),
    ("voice narration isolates speaking changed failures", VoiceNarrationIsolatesSpeakingChangedFailures),
    ("overwrites read-only settings file", OverwriteReadOnlySettingsFile),
    ("json stores ignore stale temp files", JsonStoresIgnoreStaleTempFiles),
    ("backs up corrupt settings file", BackupCorruptSettingsFile),
    ("transient settings read failures preserve the file", TransientSettingsReadFailuresPreserveFile),
    ("backs up corrupt scenario template file", BackupCorruptScenarioTemplateFile),
    ("overwrites read-only scenario template file", OverwriteReadOnlyScenarioTemplateFile),
    ("scenario template load skips null records", ScenarioTemplateLoadSkipsNullRecords),
    ("scenario template restores dynamic roster", ScenarioTemplateRestoresDynamicRoster),
    ("provider reachability clamps probe timeout", ProviderReachabilityClampsProbeTimeout),
    ("provider reachability copies status metadata", ProviderReachabilityCopiesStatusMetadata),
    ("provider reachability preserves API mode", ProviderReachabilityPreservesApiMode),
    ("provider reachability formats provider-specific offline hints", ProviderReachabilityFormatsProviderSpecificOfflineHints),
    ("provider reachability preserves completion failure during refresh", ProviderReachabilityPreservesCompletionFailureDuringRefresh),
    ("provider reachability merges status after concurrent saves", ProviderReachabilityMergesStatusAfterConcurrentSaves),
    ("provider reachability rejects stale status after identity changes", ProviderReachabilityRejectsStaleStatusAfterIdentityChanges),
    ("provider operations publish causal universal statuses", ProviderOperationsPublishCausalUniversalStatuses),
    ("provider configuration control applies atomic secret-safe patches", ProviderConfigurationControlAppliesAtomicSecretSafePatches),
    ("provider model configuration persists aliases causally without routing or residency", ProviderModelConfigurationPersistsAliasesCausallyWithoutRoutingOrResidency),
    ("provider catalog projection separates loaded and available evidence", ProviderCatalogProjectionSeparatesLoadedAndAvailableEvidence),
    ("provider catalog projection merges transitive aliases", ProviderCatalogProjectionMergesTransitiveAliases),
    ("provider catalog projection preserves llama and compatible truth", ProviderCatalogProjectionPreservesLlamaAndCompatibleTruth),
    ("provider catalog projection rejects stale generations", ProviderCatalogProjectionRejectsStaleGenerations),
    ("provider model assignment batches shared projection state", ProviderModelAssignmentBatchesSharedProjectionState),
    ("provider model assignment persists dynamic targets atomically", ProviderModelAssignmentPersistsDynamicTargetsAtomically),
    ("provider optional Default preserves explicit routes and dormant overrides", ProviderOptionalDefaultPreservesExplicitRoutesAndDormantOverrides),
    ("provider model assignment rejects stale and inactive targets", ProviderModelAssignmentRejectsStaleAndInactiveTargets),
    ("provider Models Default assignment survives host refresh", ProviderModelsDefaultAssignmentSurvivesHostRefresh),
    ("provider Models lifecycle uses confirmed LM Studio heartbeat", ProviderModelsLifecycleUsesConfirmedLmStudioHeartbeat),
    ("provider Models configuration reload handles provider default and uncertain mutations", ProviderModelsConfigurationReloadHandlesProviderDefaultAndUncertainMutations),
    ("provider Models stale residency merge remains bounded and provider neutral", ProviderModelsStaleResidencyMergeRemainsBoundedAndProviderNeutral),
    ("provider Models refresh coalesces and disposes queued work", ProviderModelsRefreshCoalescesAndDisposesQueuedWork),
    ("provider runtime rejects stale probe persistence", ProviderRuntimeRejectsStaleProbePersistence),
    ("provider runtime treats timeout changes as stale probe identity", ProviderRuntimeTreatsTimeoutChangesAsStaleProbeIdentity),
    ("provider runtime caps and redacts model catalogs", ProviderRuntimeCapsAndRedactsModelCatalogs),
    ("provider secret protection rewraps ambiguous legacy prefixes", ProviderSecretProtectionRewrapsAmbiguousLegacyPrefixes),
    ("NVIDIA telemetry probe cache bounds process launches", NvidiaTelemetryProbeCacheBoundsProcessLaunches),
    ("provider settings reset stale readiness on identity changes", ProviderSettingsResetStaleReadinessOnIdentityChanges),
    ("provider routing keeps current native options", ProviderRoutingKeepsCurrentNativeOptions),
    ("llama.cpp settings refresh preserves router model discovery", LlamaCppSettingsRefreshPreservesRouterModelDiscovery),
    ("llama.cpp runtime inspection extracts safe observed evidence", LlamaCppRuntimeInspectionExtractsSafeObservedEvidence),
    ("llama.cpp runtime inspection degrades optional endpoints independently", LlamaCppRuntimeInspectionDegradesOptionalEndpointsIndependently),
    ("llama.cpp runtime continues after an optional transport failure", LlamaCppRuntimeContinuesAfterOptionalTransportFailure),
    ("llama.cpp runtime gives each optional probe an independent timeout", LlamaCppRuntimeGivesEachOptionalProbeAnIndependentTimeout),
    ("llama.cpp runtime continues after an oversized optional response", LlamaCppRuntimeContinuesAfterOversizedOptionalResponse),
    ("llama.cpp runtime caps source entries and projects partial evidence", LlamaCppRuntimeCapsSourceEntriesAndProjectsPartialEvidence),
    ("llama.cpp runtime lifecycle is capability safe and cancelable", LlamaCppRuntimeLifecycleIsCapabilitySafeAndCancelable),
    ("llama.cpp runtime presentation formats only observed evidence", LlamaCppRuntimePresentationFormatsOnlyObservedEvidence),
    ("llama.cpp runtime presentation gates router lifecycle actions", LlamaCppRuntimePresentationGatesRouterLifecycleActions),
    ("llama.cpp runtime publishes causal universal statuses", LlamaCppRuntimePublishesCausalUniversalStatuses),
    ("llama.cpp settings surface stays capability driven and accessible", LlamaCppSettingsSurfaceStaysCapabilityDrivenAndAccessible),
    ("auto configure keeps low VRAM to one model", AutoConfigureLowVramSingleModel),
    ("auto configure spreads high VRAM model variety", AutoConfigureHighVramVariety),
    ("auto configure prefers useful multi GPU fit", AutoConfigurePrefersUsefulMultiGpuFit),
    ("lm studio catalog parses native model metadata", LmStudioCatalogParsesNativeModelMetadata),
    ("lm studio catalog bounds native response evidence", LmStudioCatalogBoundsNativeResponseEvidence),
    ("ollama catalog parses native model metadata", OllamaCatalogParsesNativeModelMetadata),
    ("ollama catalog streams and bounds native responses", OllamaCatalogStreamsAndBoundsNativeResponses),
    ("ollama catalog rejects malformed evidence and preserves tags", OllamaCatalogRejectsMalformedEvidenceAndPreservesTags),
    ("ollama catalog caps source entries and projects partial evidence", OllamaCatalogCapsSourceEntriesAndProjectsPartialEvidence),
    ("lm studio catalog handles invalid native URL", LmStudioCatalogHandlesInvalidNativeUrl),
    ("lm studio catalog sends bearer token", LmStudioCatalogSendsBearerToken),
    ("lm studio provider surfaces nested native errors", LmStudioProviderSurfacesNestedNativeErrors),
    ("lm studio model download starts native job", LmStudioModelDownloadStartsNativeJob),
    ("lm studio model download checks status", LmStudioModelDownloadChecksStatus),
    ("ollama model pull starts native request", OllamaModelPullStartsNativeRequest),
    ("native provider operations propagate caller cancellation", NativeProviderOperationsPropagateCallerCancellation),
    ("provider reachability propagates caller cancellation", ProviderReachabilityPropagatesCallerCancellation),
    ("model preload sends bearer token", ModelPreloadSendsBearerToken),
    ("model preload caps requested context to native max", ModelPreloadCapsRequestedContextToNativeMax),
    ("model preload reloads low-context native instance", ModelPreloadReloadsLowContextNativeInstance),
    ("model preload reloads unknown-context native instance", ModelPreloadReloadsUnknownContextNativeInstance),
    ("model preload fails when loaded instance ids are missing", ModelPreloadFailsWhenLoadedInstanceIdsAreMissing),
    ("model preload resolves sanitized lm studio path key", ModelPreloadResolvesSanitizedLmStudioPathKey),
    ("model unload sends bearer token", ModelUnloadSendsBearerToken),
    ("model unload resolves sanitized lm studio path key", ModelUnloadResolvesSanitizedLmStudioPathKey),
    ("model preload uses Ollama keep alive", ModelPreloadUsesOllamaKeepAlive),
    ("model unload uses Ollama keep alive zero", ModelUnloadUsesOllamaKeepAliveZero),
    ("model preload handles invalid Ollama URL", ModelPreloadHandlesInvalidOllamaUrl),
    ("auto configure uses lm studio native metadata", AutoConfigureUsesLmStudioNativeMetadata),
    ("auto configure native mode uses native catalog first", AutoConfigureNativeModeUsesNativeCatalogFirst),
    ("auto configure ollama native ignores lm studio default endpoint", AutoConfigureOllamaNativeIgnoresLmStudioDefaultEndpoint),
    ("auto configure llama native stays on the configured endpoint", AutoConfigureLlamaNativeStaysOnConfiguredEndpoint),
    ("auto configure detects lm studio native catalog on default endpoint", AutoConfigureDetectsLmStudioNativeCatalogOnDefaultEndpoint),
    ("auto configure native fallback uses compatible mode", AutoConfigureNativeFallbackUsesCompatibleMode),
    ("auto configure sends bearer token", AutoConfigureSendsBearerToken),
    ("role style catalog normalizes labels and chips", RoleStyleCatalogNormalizesLabelsAndChips),
    ("role style catalog formats voice adherence cues", RoleStyleCatalogFormatsVoiceAdherenceCues),
    ("agent memory coordinator normalizes notes", AgentMemoryCoordinatorNormalizesNotes),
    ("agent board coordinator formats statuses", AgentBoardCoordinatorFormatsStatuses),
    ("agent board coordinator disables mode buttons while busy", AgentBoardCoordinatorDisablesModeButtonsWhileBusy),
    ("agent runbook persists stable workflow and recovers interruptions", AgentRunbookPersistsStableWorkflowAndRecoversInterruptions),
    ("agent workspace empty state stays compact", AgentWorkspaceEmptyStateStaysCompact),
    ("agent workspace command preview gates execution", AgentWorkspaceCommandPreviewGatesExecution),
    ("agent workspace command runner captures terminal output", AgentWorkspaceCommandRunnerCapturesTerminalOutput),
    ("agent workspace command rejects invalid timeouts", AgentWorkspaceCommandRejectsInvalidTimeouts),
    ("agent workspace clipboard helper handles busy clipboard", AgentWorkspaceClipboardHelperHandlesBusyClipboard),
    ("agent workspace file receipt scan is bounded", AgentWorkspaceFileReceiptScanIsBounded),
    ("agent workspace profile directory scan is bounded", AgentWorkspaceProfileDirectoryScanIsBounded),
    ("agent workspace profile skips oversized package json", AgentWorkspaceProfileSkipsOversizedPackageJson),
    ("agent workspace generated commands reject shell metacharacters", AgentWorkspaceGeneratedCommandsRejectShellMetacharacters),
    ("agent workspace bounded readers and candidates stop at limits", AgentWorkspaceBoundedReadersAndCandidatesStopAtLimits),
    ("agent impact explorer renders evidence and stages focused tests", AgentImpactExplorerRendersEvidenceAndStagesFocusedTests),
    ("agent impact explorer rejects untrusted focused commands", AgentImpactExplorerRejectsUntrustedFocusedCommands),
    ("agent impact explorer keeps unavailable evidence honest", AgentImpactExplorerKeepsUnavailableEvidenceHonest),
    ("agent impact explorer discards stale workspace evidence", AgentImpactExplorerDiscardsStaleWorkspaceEvidence),
    ("agent impact explorer bounds inspectable focused test evidence", AgentImpactExplorerBoundsInspectableFocusedTestEvidence),
    ("agent impact explorer predicts off dispatcher with cancellation", AgentImpactExplorerPredictsOffDispatcherWithCancellation),
    ("agent solution doctor presents typed workspace actions", AgentSolutionDoctorPresentsTypedWorkspaceActions),
    ("agent workspace stages builder command proposals", AgentWorkspaceStagesBuilderCommandProposals),
    ("agent workspace blocks command approval during chat", AgentWorkspaceBlocksCommandApprovalDuringChat),
    ("agent workspace restores chat after restart", AgentWorkspaceRestoresChatAfterRestart),
    ("operator turn coordinator disables input during busy work", OperatorTurnCoordinatorDisablesInputDuringBusyWork),
    ("operator turn factory ingestion preserves exact public input", OperatorTurnCoordinatorPreservesFactoryPublicIngestionBoundaries),
    ("operator turn coordinator suggests interventions", OperatorTurnCoordinatorSuggestsInterventions),
    ("transcript action coordinator exposes automation names", TranscriptActionCoordinatorExposesAutomationNames),
    ("transcript export coordinator previews scope", TranscriptExportCoordinatorPreviewsScope),
    ("shell file export replaces read-only targets", ShellFileExportReplacesReadOnlyTargets),
    ("shell process launcher reports failures", ShellProcessLauncherReportsFailures),
    ("agent performance coordinator aggregates native telemetry", AgentPerformanceCoordinatorAggregatesNativeTelemetry),
    ("metric sparkline control measures responsively", MetricSparklineControlMeasuresResponsively),
    ("agent world layout maps active chat state", AgentWorldLayoutMapsActiveChatState),
    ("agent world pulse summarizes live telemetry", AgentWorldPulseSummarizesLiveTelemetry),
    ("agent world cue ribbon summarizes live events", AgentWorldCueRibbonSummarizesLiveEvents),
    ("agent world collision solver separates crowded robots", AgentWorldCollisionSolverSeparatesCrowdedRobots),
    ("agent world minimap markers stay inside frame", AgentWorldMiniMapMarkersStayInsideFrame),
    ("agent world minimap tracks camera focus", AgentWorldMiniMapTracksCameraFocus),
    ("agent world minimap markers expose automation labels", AgentWorldMiniMapMarkersExposeAutomationLabels),
    ("agent world 3d control uses extended accent fallbacks", AgentWorld3DControlUsesExtendedAccentFallbacks),
    ("agent world inspector close button exposes automation name", AgentWorldInspectorCloseButtonExposesAutomationName),
    ("agent world 3d control renders snapshot", AgentWorld3DControlRendersSnapshot),
    ("agent world 3d control renders narrator identity cues", AgentWorld3DControlRendersNarratorIdentityCues),
    ("agent world respects reduced motion and reuses frame state", AgentWorldRespectsReducedMotionAndReusesFrameState),
    ("agent world skips rebuild for unchanged snapshots", AgentWorldSkipsRebuildForUnchangedSnapshots),
    ("agent world empty snapshot resets transient world state", AgentWorldEmptySnapshotResetsTransientWorldState),
    ("agent world follow camera tracks speaker changes until manual selection", AgentWorldFollowCameraTracksSpeakerChangesUntilManualSelection),
    ("agent world resets transient state on session change", AgentWorldResetsTransientStateOnSessionChange),
    ("agent world hud resizes for narrow panes", AgentWorldHudResizesForNarrowPanes),
    ("agent world header badge fits long speaker names", AgentWorldHeaderBadgeFitsLongSpeakerNames),
    ("agent world keyboard controls camera and inspector", AgentWorldKeyboardControlsCameraAndInspector),
    ("agent world overview restores follow pan offset", AgentWorldOverviewRestoresFollowPanOffset),
    ("agent world bubble placement stays visible at edges", AgentWorldBubblePlacementStaysVisibleAtEdges),
    ("agent world material cache is bounded without invalidating live geometry", AgentWorldMaterialCacheIsBoundedWithoutInvalidatingLiveGeometry),
    ("main window skips hidden world snapshot refresh", MainWindowSkipsHiddenWorldSnapshotRefresh),
    ("arena operation coordinator selects operation mode", ArenaOperationCoordinatorSelectsOperationMode),
    ("factory mode readiness requires eligible public Operator input", FactoryModeReadinessRequiresEligiblePublicOperatorInput),
    ("arena readiness honors optional default routing", ArenaReadinessHonorsOptionalDefaultRouting),
    ("stale provider projection cannot undo factory Operator readiness", StaleProviderProjectionCannotUndoFactoryOperatorReadiness),
    ("control plane Factory prerequisites use the durable snapshot", ControlPlaneFactoryPrerequisitesUseDurableSnapshot),
    ("factory mode toggle persists across concurrency with safe audit payload", FactoryModeTogglePersistsAcrossConcurrencyWithSafeAuditPayload),
    ("factory mode UI actions remain unavailable and honest", FactoryModeUiActionsRemainUnavailableAndHonest),
    ("factory mode failed completions keep System-event status honest", FactoryModeFailedCompletionsKeepSystemEventStatusHonest),
    ("scenario workflow separates replay and copy actions during auto chat", ScenarioWorkflowSeparatesReplayAndCopyDuringAutoChat),
    ("scenario workflow clipboard helper handles busy clipboard", ScenarioWorkflowClipboardHelperHandlesBusyClipboard),
    ("scenario workflow preserves generation history selection", ScenarioWorkflowPreservesGenerationHistorySelection),
    ("match setup coordinator plans rivalry matrix safely", MatchSetupCoordinatorPlansRivalryMatrixSafely),
    ("saved state workflow ignores stale checkpoint refresh", SavedStateWorkflowIgnoresStaleCheckpointRefresh),
    ("transcript adjunct helpers format labels", TranscriptAdjunctHelpersFormatLabels),
    ("diagnostics wait for the first scored turn", DiagnosticsWaitForFirstScoredTurn),
    ("transcript battle review summarizes match", TranscriptBattleReviewSummarizesMatch),
    ("transcript run trace summarizes spans", TranscriptRunTraceSummarizesSpans),
    ("arena evaluation captures repeatable secret-free evidence", ArenaEvaluationCapturesRepeatableSecretFreeEvidence),
    ("arena evaluation keeps factory and mixed evidence honest", ArenaEvaluationKeepsFactoryAndMixedEvidenceHonest),
    ("arena evaluation compares same scenarios and classifies regressions", ArenaEvaluationComparesSameScenarioAndClassifiesRegression),
    ("arena evaluation QA reports explicit evidence states", ArenaEvaluationQaReportsExplicitEvidenceStates),
    ("arena evaluation history is bounded atomic and corrupt-recovering", ArenaEvaluationHistoryIsBoundedAtomicAndRecoversCorruption),
    ("arena evaluation presentation exposes non-colour model comparisons", ArenaEvaluationPresentationExposesNonColourModelComparisons),
    ("arena evaluation surface stays replayable and accessible", ArenaEvaluationSurfaceStaysReplayableAndAccessible),
    ("Experiment Lab expands matrices deterministically and honestly", ExperimentLabExpandsMatricesDeterministicallyAndHonestly),
    ("Experiment Lab registers only backed accessible features", ExperimentLabRegistersOnlyBackedAccessibleFeatures),
    ("Experiment Lab control plane exposes only safe registered feature state", ExperimentLabControlPlaneExposesOnlySafeRegisteredFeatureState),
    ("Experiment Lab feature selection contains refresh failures and stale completions", ExperimentLabFeatureSelectionContainsRefreshFailuresAndStaleCompletions),
    ("Experiment Lab coordinator persists fork pack rubric and claim evidence", ExperimentLabCoordinatorPersistsForkPackRubricAndClaimEvidence),
    ("Experiment Lab rejects stale claim picker provenance after session change", ExperimentLabRejectsClaimPickerAcrossSessionChange),
    ("Experiment Lab restores interrupted matrices only after approval", ExperimentLabRestoresInterruptedMatrixOnlyAfterApproval),
    ("Experiment Lab restores the newest representable durable definition", ExperimentLabRestoresNewestRepresentableDefinition),
    ("Experiment Lab rechecks restart recovery after an observed owner exits", ExperimentLabRechecksRecoveryAfterObservedOwnerExits),
    ("Experiment Lab preserves restored references across source drift", ExperimentLabPreservesRestoredReferencesAcrossSourceDrift),
    ("Experiment Lab closes completed crash windows without duplicate trials", ExperimentLabClosesCompletedCrashWindowWithoutDuplicateTrials),
    ("Experiment Lab leaves unsupported durable matrices untouched", ExperimentLabLeavesUnsupportedDurableMatrixUntouched),
    ("Experiment Lab imports legacy packs with explicit migration receipts", ExperimentLabImportsLegacyPacksWithMigrationReceipt),
    ("Experiment Lab shell navigation preserves existing surface contracts", ExperimentLabShellNavigationPreservesExistingSurfaceContracts),
    ("Experiment Lab production composition shares observed provider and registers every surface", ExperimentLabProductionCompositionSharesObservedProviderAndRegistersEverySurface),
    ("Experiment Lab provider judge persists traced inferred evidence", ExperimentLabProviderJudgePersistsTracedInferredEvidence),
    ("Experiment Lab provider judge cancellation owns its lifetime", ExperimentLabProviderJudgeCancellationOwnsItsLifetime),
    ("Experiment Lab blind judge conceals identities until durable submit", ExperimentLabBlindJudgeConcealsIdentitiesUntilDurableSubmit),
    ("transcript card renderer labels internet cards", TranscriptCardRendererLabelsInternetCards),
    ("transcript card renderer hosts accessible public Operator group card", TranscriptCardRendererHostsAccessiblePublicOperatorCard),
    ("transcript card renderer hides internet metadata by default", TranscriptCardRendererHidesInternetMetadataByDefault),
    ("transcript card renderer shows source globe on sourced turns", TranscriptCardRendererShowsSourceGlobeOnSourcedTurns),
    ("transcript card renderer exposes model stats and persistent actions", TranscriptCardRendererExposesModelStatsAndPersistentActions),
    ("transcript card renderer omits unavailable stats and resolves responsive tiers", TranscriptCardRendererOmitsUnavailableStatsAndResolvesResponsiveTiers),
    ("transcript mutation coordinator formats statuses", TranscriptMutationCoordinatorFormatsStatuses),
    ("arena run coordinator formats statuses", ArenaRunCoordinatorFormatsStatuses),
    ("arena run coordinator drains auto chat on stop", ArenaRunCoordinatorDrainsAutoChatOnStop),
    ("arena run coordinator survives provider and cancellation failures", ArenaRunCoordinatorSurvivesProviderAndCancellationFailures),
    ("operator draft receipts summarize routes", OperatorDraftReceiptsSummarizeRoutes),
    ("arena session mutation coordinator normalizes settings", ArenaSessionMutationCoordinatorNormalizesSettings),
    ("session overview coordinator formats summaries", SessionOverviewCoordinatorFormatsSummaries),
    ("shell ui helpers blend brushes", ShellUiHelpersBlendBrushes),
    ("dialog chrome close button exposes automation name", DialogChromeCloseButtonExposesAutomationName),
    ("custom dialogs preserve modal accessibility and responsive bounds", CustomDialogsPreserveModalAccessibilityAndResponsiveBounds),
    ("agent accent service normalizes colors", AgentAccentServiceNormalizesColors),
    ("window chrome service packs color refs", WindowChromeServicePacksColorRefs),
    ("app starts internet backend lazily", AppStartsInternetBackendLazily),
    ("searxng supervisor plans bundled launch", SearxngSupervisorPlansBundledLaunch),
    ("searxng supervisor cleans canceled startup", SearxngSupervisorCleansCanceledStartup),
    ("searxng supervisor stop is a startup barrier", SearxngSupervisorStopIsStartupBarrier),
    ("searxng supervisor disposal cleans delayed start", SearxngSupervisorDisposalCleansDelayedStart),
    ("searxng supervisor replaces an unhealthy owned child", SearxngSupervisorReplacesUnhealthyOwnedChild),
    ("searxng supervisor rejects stale health after child exit", SearxngSupervisorRejectsStaleHealthAfterChildExit),
    ("searxng supervisor rejects stale initial health after owned exit", SearxngSupervisorRejectsStaleInitialHealthAfterOwnedExit),
    ("searxng supervisor initial health honors stop generation", SearxngSupervisorInitialHealthHonorsStopGeneration),
    ("searxng supervisor reports backend health", SearxngSupervisorReportsBackendHealth),
    ("internet diagnostics report real search metadata", InternetDiagnosticsReportSearchMetadata),
    ("internet diagnostics supersede older runs", InternetDiagnosticsSupersedeOlderRuns),
    ("internet diagnostics keep cancellation alive while superseded runs unwind", InternetDiagnosticsKeepCancellationAliveWhileSupersededRunsUnwind),
    ("internet diagnostics keep cancellation alive while disposed runs unwind", InternetDiagnosticsKeepCancellationAliveWhileDisposedRunsUnwind),
    ("internet diagnostics survive cancellation callback failures", InternetDiagnosticsSurviveCancellationCallbackFailures),
    ("internet backend health keeps cancellation alive while superseded refreshes unwind", InternetBackendHealthKeepsCancellationAliveWhileSupersededRefreshesUnwind),
    ("internet workflow persists direct toggle and controls backend", InternetWorkflowStartsAndStopsBackendWithToggle),
    ("internet toggle persists session immediately", InternetTogglePersistsSessionImmediately),
    ("internet toggle persistence stays with originating session", InternetTogglePersistenceStaysWithOriginatingSession),
    ("internet diagnostics clean up temporary backend while off", InternetDiagnosticsCleanUpTemporaryBackendWhileOff),
    ("internet workflow formats backend health", InternetWorkflowFormatsBackendHealth),
    ("internet workflow formats actionable diagnostics", InternetWorkflowFormatsActionableDiagnostics),
    ("release scripts protect installer distributions", ReleaseScriptsProtectInstallerDistributions),
    ("app icon resource is packaged", AppIconResourceIsPackaged),
    ("user guide app icon image source loads", UserGuideAppIconImageSourceLoads),
    ("user guide header icon image source loads", UserGuideHeaderIconImageSourceLoads),
    ("user guide read handles missing files", UserGuideReadHandlesMissingFiles),
    ("user guide search matches unordered tokens", UserGuideSearchMatchesUnorderedTokens),
    ("user guide article header trims long titles", UserGuideArticleHeaderTrimsLongTitles),
    ("provider reachability coordinator formats popup state", ProviderReachabilityCoordinatorFormatsPopupState),
    ("provider reachability projects one coherent UI generation", ProviderReachabilityProjectsOneCoherentUiGeneration),
    ("truncate respects its limit and suffix", TruncateRespectsItsLimitAndSuffix),
    ("session picker hides empty sessions without losing reach", SessionPickerHidesEmptySessionsWithoutLosingReach),
    ("session token accounting reports totals and pressure", SessionTokenAccountingReportsTotalsAndPressure),
    ("cross session search attributes and caps hits", CrossSessionSearchAttributesAndCapsHits),
    ("idle polling cadence only when nothing is running", IdlePollingCadenceOnlyWhenNothingIsRunning),
    ("transcript row sync preserves unchanged tail", TranscriptRowSyncPreservesUnchangedTail),
    ("advertised shortcuts are handled", AdvertisedShortcutsAreHandled),
    ("shell state changes reach the control plane from both routes", ShellStateChangesReachTheControlPlaneFromBothRoutes),
    ("command palette ranks matches predictably", CommandPaletteRanksMatchesPredictably),
    ("empty and off states are not styled as failures", EmptyAndOffStatesAreNotStyledAsFailures),
    ("dependency index check ignores line endings", DependencyIndexCheckIgnoresLineEndings),
    ("every human drivable event has a shared publisher", EveryHumanDrivableEventHasASharedPublisher),
    ("control plane key parsing accepts what people write", ControlPlaneKeyParsingAcceptsWhatPeopleWrite),
    ("screenshots and modals do not misreport the app", ScreenshotsAndModalsDoNotMisreportTheApp),
    ("settings and match setup do not share the window", SettingsAndMatchSetupDoNotShareTheWindow),
    ("narrowing the window does not hide the rail for good", NarrowingTheWindowDoesNotHideTheRailForGood),
    ("crashes leave something behind", CrashesLeaveSomethingBehind),
    ("an unknown theme is refused rather than substituted", AnUnknownThemeIsRefusedRatherThanSubstituted),
    ("generation refuses unknown options instead of substituting", GenerationRefusesUnknownOptionsInsteadOfSubstituting),
    ("a blocked arena operation is not reported as completed", ABlockedArenaOperationIsNotReportedAsCompleted),
    ("provider error text cannot be a whole web page", ProviderErrorTextCannotBeAWholeWebPage),
    ("rejected workspace paths are reported as failures", RejectedWorkspacePathsAreReportedAsFailures),
    ("empty arguments are not mistaken for missing ones", EmptyArgumentsAreNotMistakenForMissingOnes),
    ("status tones avoid agent identity accents", StatusTonesAvoidAgentIdentityAccents),
    ("shell navigation coordinator selects themes", ShellNavigationCoordinatorSelectsThemes),
    ("app settings coordinator selects provider focus", AppSettingsCoordinatorSelectsProviderFocus),
    ("coordinator render contracts cover smoke states", CoordinatorRenderContractsCoverSmokeStates),
    ("transcript list coordinator selects retryable turns", TranscriptListCoordinatorSelectsRetryableTurns),
    ("transcript empty state reflects readiness and filters", TranscriptEmptyStateReflectsReadinessAndFilters),
    ("transcript view coordinator normalizes view state", TranscriptViewCoordinatorNormalizesViewState),
    ("transcript view coordinator adapts dashboard widths", TranscriptViewCoordinatorAdaptsDashboardWidths),
    ("transcript search coordinator keeps close available when empty", TranscriptSearchCoordinatorKeepsCloseAvailableWhenEmpty),
    ("dispatcher debouncer coalesces and flushes work", DispatcherDebouncerCoalescesAndFlushesWork),
    ("transcript search coordinator debounces text refresh", TranscriptSearchCoordinatorDebouncesTextRefresh),
    ("transcript search coordinator debounces collaborate result rendering", TranscriptSearchCoordinatorDebouncesCollaborateResultRendering),
    ("transcript search coordinator keeps surface queries separate", TranscriptSearchCoordinatorKeepsSurfaceQueriesSeparate),
    ("transcript search coordinator exposes row automation", TranscriptSearchCoordinatorExposesRowAutomation),
    ("collaborate history keeps duplicate display titles", CollaborateHistoryKeepsDuplicateDisplayTitles),
    ("collaborate history filters empty exchanges before cap", CollaborateHistoryFiltersEmptyExchangesBeforeCap),
    ("collaborate history save preserves caller objects", CollaborateHistorySavePreservesCallerObjects),
    ("collaborate history load skips null records", CollaborateHistoryLoadSkipsNullRecords),
    ("transient collaborate history reads preserve the file", TransientCollaborateHistoryReadsPreserveFile),
    ("collaborate search finds saved chat content", CollaborateSearchFindsSavedChatContent),
    ("collaborate recent chat metadata summarizes runs", CollaborateRecentChatMetadataSummarizesRuns),
    ("collaborate recent compare summarizes run deltas", CollaborateRecentCompareSummarizesRunDeltas),
    ("collaborate recent filters organize saved runs", CollaborateRecentFiltersOrganizeSavedRuns),
    ("collaborate recent list summarizes saved runs", CollaborateRecentListSummarizesSavedRuns),
    ("collaborate recent actions fork and repeat chats", CollaborateRecentActionsForkAndRepeatChats),
    ("collaborate preflight accepts role-specific models", CollaboratePreflightAcceptsRoleSpecificModels),
    ("collaborate run plan summarizes model calls", CollaborateRunPlanSummarizesModelCalls),
    ("collaborate interruption exchanges remain persistable", CollaborateInterruptionExchangesRemainPersistable),
    ("collaborate memory notes persist with conversations", CollaborateMemoryNotesPersistWithConversations),
    ("collaborate prompt budget summarizes context", CollaboratePromptBudgetSummarizesContext),
    ("collaborate context receipt summarizes payload", CollaborateContextReceiptSummarizesPayload),
    ("collaborate table summaries skip markdown dividers", CollaborateTableSummariesSkipMarkdownDividers),
    ("collaborate empty state stays compact", CollaborateEmptyStateStaysCompact),
    ("collaborate prompt templates preserve drafts", CollaboratePromptTemplatesPreserveDrafts),
    ("collaborate trace follow-up prompt preserves drafts", CollaborateTraceFollowUpPromptPreservesDrafts),
    ("collaborate run review summarizes traces", CollaborateRunReviewSummarizesTraces),
    ("collaborate control review exposes saved trace", CollaborateControlReviewExposesSavedTrace),
    ("collaborate conversation export includes run review and trace", CollaborateConversationExportIncludesRunReviewAndTrace),
    ("collaborate clear syncs shell status", CollaborateClearSyncsShellStatus),
    ("collaborate team debate header summarizes trace", CollaborateTeamDebateHeaderSummarizesTrace),
    ("collaborate blank role completion falls back to shared model", CollaborateBlankRoleCompletionFallsBackToSharedModel),
    ("collaborate send preserves history save failures", CollaborateSendPreservesHistorySaveFailures),
    ("collaborate failed sends are saved in history", CollaborateFailedSendsAreSavedInHistory),
    ("snapshot view mapper preserves provider telemetry", SnapshotViewMapperPreservesProviderTelemetry),
    ("snapshot view mapper attaches latest internet sources to agents", SnapshotViewMapperAttachesLatestInternetSourcesToAgents),
    ("agent internet sources presenter formats copy text", AgentInternetSourcesPresenterFormatsCopyText),
    ("custom match summary coordinator normalizes card text", CustomMatchSummaryCoordinatorNormalizesCardText),
    ("factory mode setup presentation discloses inactive Arena behavior", FactoryModeSetupPresentationDisclosesInactiveArenaBehavior),
    ("scenario seed inspector coordinator formats metadata", ScenarioSeedInspectorCoordinatorFormatsMetadata),
    ("provider quick setup coordinator formats defaults", ProviderQuickSetupCoordinatorFormatsDefaults),
    ("main window combobox template uses theme resources", MainWindowComboBoxTemplateUsesThemeResources),
    ("theme brush defaults mirror the default palette", ThemeBrushDefaultsMirrorTheDefaultPalette),
    ("design token resources match their WPF contract", DesignTokenResourcesMatchTheirWpfContract),
    ("main window collaborate prompt uses multiline alignment", MainWindowCollaboratePromptUsesMultilineAlignment),
    ("main window collaborate prompt assist buttons stay compact", MainWindowCollaboratePromptAssistButtonsStayCompact),
    ("main window agent section is top level", MainWindowAgentSectionIsTopLevel),
    ("shell command state maps contextual workspace commands", ShellCommandStateMapsContextualWorkspaceCommands),
    ("main window contextual command hosts and provider metrics stay wired", MainWindowContextualCommandHostsAndProviderMetricsStayWired),
    ("main window navigation transitions preserve context", MainWindowNavigationTransitionsPreserveContext),
    ("provider Models heartbeat follows hosted effective visibility", ProviderModelsHeartbeatFollowsHostedEffectiveVisibility),
    ("main window agent command rail exposes approval contract", MainWindowAgentCommandRailExposesApprovalContract),
    ("main window export button switches context", MainWindowExportButtonSwitchesContext),
    ("main window match setup controls expose automation", MainWindowMatchSetupControlsExposeAutomation),
    ("main window factory mode toggle exposes automation and control state", MainWindowFactoryModeToggleExposesAutomationAndControlState),
    ("AI Lab header avoids duplicate match setup action", AiLabHeaderAvoidsDuplicateMatchSetupAction),
    ("main window voice tts settings expose automation", MainWindowVoiceTtsSettingsExposeAutomation),
    ("main window debug controls remain discoverable", MainWindowDebugControlsRemainDiscoverable),
    ("main window internet settings use one direct toggle", MainWindowInternetSettingsUseOneDirectToggle),
    ("main window model provider uses progressive disclosure", MainWindowModelProviderUsesProgressiveDisclosure),
    ("settings search expands nested disclosures and restores state", SettingsSearchExpandsNestedDisclosuresAndRestoresState),
    ("main window match setup matrix has clear action", MainWindowMatchSetupMatrixHasClearAction),
    ("main window operator quick interventions expose automation", MainWindowOperatorQuickInterventionsExposeAutomation),
    ("main window operator turn text uses multiline scroll affordance", MainWindowOperatorTurnTextUsesMultilineScrollAffordance),
    ("main window transcript search popup sizes responsively", MainWindowTranscriptSearchPopupSizesResponsively),
    ("main window overlays preserve keyboard and accessibility contracts", MainWindowOverlaysPreserveKeyboardAndAccessibilityContracts),
    ("main window adaptive shell layout stays wired", MainWindowAdaptiveShellLayoutStaysWired),
    ("main window live agents viewport stays constrained", MainWindowLiveAgentsViewportStaysConstrained),
    ("main window empty export status releases toolbar space", MainWindowEmptyExportStatusReleasesToolbarSpace),
    ("main window right rail collapse preserves keyboard context", MainWindowRightRailCollapsePreservesKeyboardContext),
    ("main window right rail adapts without changing preferences", MainWindowRightRailAdaptsWithoutChangingPreferences),
    ("main window snapshot refresh skips unchanged session scans", MainWindowSnapshotRefreshSkipsUnchangedSessionScans),
    ("control plane parses commands and stable responses", ControlPlaneParsesCommandsAndStableResponses),
    ("control plane status projection preserves legacy and bounds typed state", ControlPlaneStatusProjectionPreservesLegacyAndBoundsTypedState),
    ("control plane status changed publishes privacy safe typed state", ControlPlaneStatusChangedPublishesPrivacySafeTypedState),
    ("control plane requires session token", ControlPlaneRequiresSessionToken),
    ("control plane isolates two concurrent owner processes", ControlPlaneIsolatesTwoConcurrentOwnerProcesses),
    ("control plane rejects oversized requests", ControlPlaneRejectsOversizedRequests),
    ("control plane stop drains active clients", ControlPlaneStopDrainsActiveClients),
    ("control plane restarts after a drained stop", ControlPlaneRestartsAfterDrainedStop),
    ("control plane async transitions do not block pending drain", ControlPlaneAsyncTransitionsDoNotBlockPendingDrain),
    ("control plane stop cancels blocked event writes", ControlPlaneStopCancelsBlockedEventWrites),
    ("control plane main window awaits lifecycle transitions", ControlPlaneMainWindowAwaitsLifecycleTransitions),
    ("control plane event queue is capped", ControlPlaneEventQueueIsCapped),
    ("control plane event queue overflow drains safely", ControlPlaneEventQueueOverflowDrainsSafely),
    ("control plane defaults on and persists its settings toggle", ControlPlaneDefaultsOnAndPersistsSettingsToggle),
    ("control plane events format json lines", ControlPlaneEventsFormatJsonLines),
    ("control plane dispatcher invokes on STA dispatcher", ControlPlaneDispatcherInvokesOnStaDispatcher),
    ("control plane known command registry covers first surface", ControlPlaneKnownCommandRegistryCoversFirstSurface),
    ("control plane powershell client exposes typed verbs", ControlPlanePowerShellClientExposesTypedVerbs),
    ("screenshot control service resolves safe paths and preserves existing files", ScreenshotControlServiceResolvesSafePathsAndPreservesExistingFiles),
    ("app screenshot handler captures a real PNG and publishes its event", AppScreenshotHandlerCapturesRealPngAndPublishesEvent),
    ("UI verification captures privacy-safe deterministic structure", UiVerificationCapturesPrivacySafeDeterministicStructure),
    ("UI verification uses semantic transcript count instead of placeholder rows", UiVerificationUsesSemanticTranscriptCountInsteadOfPlaceholderRows),
    ("UI verification control handler bounds window and routes commands", UiVerificationControlHandlerBoundsWindowAndRoutesCommands),
    ("UI verification binds Experiment Lab evidence to the observed feature", UiVerificationBindsExperimentEvidenceToObservedFeature),
    ("shared pointer feedback releases dead STA motion subscriptions", SharedPointerFeedbackReleasesDeadStaMotionSubscriptions),
    ("UI verification advances privacy-safe focus and overrides motion only in isolation", UiVerificationAdvancesPrivacySafeFocusAndOverridesMotionOnlyInIsolation),
    ("UI verification captures one owner-bound atomic shell focus cycle", UiVerificationCapturesOwnerBoundAtomicShellFocusCycle),
    ("workspace page header hosts responsive accessible contract", WorkspacePageHeaderHostsResponsiveAccessibleContract),
    ("provider Models surface hosts responsive accessible contract", ProviderModelAssignmentsControlHostsResponsiveAccessibleContract),
    ("provider Models surface raises immediate truthful events", ProviderModelAssignmentsControlRaisesImmediateTruthfulEvents),
    ("provider Models surface transfers exclusive targets optimistically", ProviderModelAssignmentsControlTransfersExclusiveTargetsOptimistically),
    ("provider Models surface hosts causal LM Studio lifecycle action", ProviderModelAssignmentsControlHostsCausalLmStudioLifecycleAction),
    ("provider Models optimization preserves incremental catalog continuity", ProviderModelsOptimizationPreservesIncrementalCatalogContinuity),
    ("provider Models optimization debounces search and filters catalog facets", ProviderModelsOptimizationDebouncesSearchAndFiltersCatalogFacets),
    ("provider Models optimization exposes groups partial evidence and assignment states", ProviderModelsOptimizationExposesGroupsPartialEvidenceAndAssignmentStates),
    ("provider Models optimization reflows at wide compact and two hundred percent", ProviderModelsOptimizationReflowsAtWideCompactAndTwoHundredPercent),
    ("provider Models pinned layout keeps Loaded visible and catalog disclosure stable", ProviderModelsPinnedLayoutKeepsLoadedVisibleAndCatalogDisclosureStable),
    ("provider Models pinned layout moves selection and uses accessible switches", ProviderModelsPinnedLayoutMovesSelectionAndUsesAccessibleSwitches),
    ("universal status center keeps four stable newest-first rows", UniversalStatusCenterKeepsFourStableNewestFirstRows),
    ("universal status center dashboard filters and restores focus", UniversalStatusCenterDashboardFiltersAndRestoresFocus),
    ("universal status center shell layout is pinned and overlay safe", UniversalStatusCenterShellLayoutIsPinnedAndOverlaySafe),
    ("application status center preserves causality and priority", ApplicationStatusCenterPreservesCausalityAndPriority),
    ("application status center coalesces expires sanitizes and clears safely", ApplicationStatusCenterCoalescesExpiresSanitizesAndClearsSafely),
    ("application status center covers residual shell feedback", ApplicationStatusCenterCoversResidualShellFeedback),
    ("provider Models configuration hosts responsive accessible contract", ProviderModelsConfigurationHostsResponsiveAccessibleContract),
    ("provider Models configuration saves rolls back and reloads causally", ProviderModelsConfigurationSavesRollsBackAndReloadsCausally),
    ("provider Models configuration reload identity switches stay causal", ProviderModelsConfigurationReloadIdentitySwitchesStayCausal),
    ("shared menu popup hosts theme focus and disabled contracts", SharedMenuPopupHostsThemeFocusAndDisabledContracts),
    ("QA screenshot render DPI preserves DIP viewport and bounds raster scale", QaScreenshotRenderDpiPreservesDipViewportAndBoundsRasterScale),
    ("real WPF automation artifact passes authoritative evidence CLI", RealWpfAutomationArtifactPassesAuthoritativeEvidenceCli),
    ("provider control handler routes commands and publishes events", ProviderControlHandlerRoutesCommandsAndPublishesEvents),
    ("provider diagnostics cache rejects switched and edited fingerprints", ProviderDiagnosticsCacheRejectsSwitchedAndEditedFingerprints),
    ("control plane main window delegates provider commands", ControlPlaneMainWindowDelegatesProviderCommands),
    ("saved state control service creates selects and restores", SavedStateControlServiceCreatesSelectsAndRestores),
    ("session fork workflow branches and sanitizes receipts", SessionForkWorkflowBranchesAndSanitizesReceipts),
    ("session fork workflow returns stable failure codes", SessionForkWorkflowReturnsStableFailureCodes),
    ("session fork control handler and PowerShell helper route safely", SessionForkControlHandlerAndPowerShellHelperRouteSafely),
    ("shell overlay control service preserves navigation contracts", ShellOverlayControlServicePreservesNavigationContracts),
    ("match setup control handler validates roster changes", MatchSetupControlHandlerValidatesRosterChanges),
    ("match setup model behavior control shares the visual mutation path", MatchSetupModelBehaviorControlSharesVisualMutationPath),
    ("match setup package codec round trips exact portable state", MatchSetupPackageCodecRoundTripsExactPortableState),
    ("match setup portability creates clean sessions and protects tokens", MatchSetupPortabilityCreatesCleanSessionsAndProtectsTokens),
    ("match setup control handler exports and imports portable packages", MatchSetupControlHandlerExportsAndImportsPortablePackages),
    ("agent roster control path persists bounded cast changes", AgentRosterControlPathPersistsBoundedCastChanges),
    ("rivalry matrix control service persists named patterns", RivalryMatrixControlServicePersistsNamedPatterns),
    ("app preference control service persists safe updates", AppPreferenceControlServicePersistsSafeUpdates),
    ("scenario generation control service generates and replays native history", ScenarioGenerationControlServiceGeneratesAndReplaysNativeHistory),
    ("control plane publishes required event vocabulary", ControlPlanePublishesRequiredEventVocabulary),
    ("control plane rejects narrator commands after End Match", ControlPlaneEndedMatchRejectsNarratorCommands),
    ("control plane navigation closes settings for main views", ControlPlaneNavigationClosesSettingsForMainViews),
    ("control plane Match Setup open owns the visible overlay", ControlPlaneMatchSetupOpenOwnsVisibleOverlay),
    ("agent solution doctor previews exact repairs and requires manual approval", AgentSolutionDoctorPreviewsExactRepairsAndRequiresManualApproval),
    ("agent solution doctor records only approved verified repair loops", AgentSolutionDoctorRecordsOnlyApprovedVerifiedRepairLoops),
    ("agent solution doctor drives structured repair evidence", AgentSolutionDoctorDrivesStructuredRepairEvidence),
    ("agent workspace profile refresh ignores stale results", AgentWorkspaceProfileRefreshIgnoresStaleResults),
    ("agent solution doctor refresh ignores stale typed results", AgentSolutionDoctorRefreshIgnoresStaleTypedResults),
    ("agent solution doctor survives legacy profile failure", AgentSolutionDoctorSurvivesLegacyProfileFailure),
    ("agent solution doctor refreshes assets after restore", AgentSolutionDoctorRefreshesAfterRestore),
    ("agent solution doctor treats structured failure as authoritative", AgentSolutionDoctorTreatsStructuredFailureAsAuthoritative),
    ("agent workspace profile refresh disposes safely", AgentWorkspaceProfileRefreshDisposesSafely),
    ("inspection lab presents exact prompt evidence honestly", InspectionLabPresentsExactPromptEvidenceHonestly),
    ("inspection lab keeps memory private until one agent is selected", InspectionLabKeepsMemoryPrivateUntilOneAgentIsSelected),
    ("inspection lab disables memory acceptance while revalidating", InspectionLabDisablesMemoryAcceptanceWhileRevalidating),
    ("inspection lab persists correction and expiry lifecycles", InspectionLabPersistsCorrectionAndExpiryLifecycles),
    ("inspection lab clears private view during session switches", InspectionLabClearsPrivateViewDuringSessionSwitch),
    ("inspection lab clears private view when session changes during mutation save", InspectionLabClearsPrivateViewWhenSessionChangesDuringMutationSave),
    ("inspection lab stays bounded responsive and accessible", InspectionLabStaysBoundedResponsiveAndAccessible),
    ("inspection lab hosts responsive theme and virtualization contracts", InspectionLabHostsResponsiveThemeAndVirtualizationContracts),
    ("resilience labs register responsive accessible features", ResilienceLabsRegisterResponsiveAccessibleFeatures),
    ("fault lab arms runs and disarms every bounded kind", FaultLabArmsRunsAndDisarmsEveryBoundedKind),
    ("routing optimizer consumes persisted evidence and requires approval", RoutingOptimizerConsumesPersistedObservedEvidenceAndRequiresApproval),
    ("routing evidence rejects logical-run self pairs", RoutingEvidenceRejectsLogicalRunSelfPairs),
    ("route application boundary serializes tracks and refreshes", RouteApplicationBoundarySerializesTracksAndRefreshes),
    ("QA Inspector rejects malicious evidence paths and content", QaInspectorRejectsMaliciousEvidencePathsAndContent),
    ("QA Inspector presents every evidence state accessibly", QaInspectorPresentsAllEvidenceStatesAccessibly),
    ("QA Inspector allows only fixed suites and cancels", QaInspectorAllowsOnlyFixedSuitesAndCancels),
    ("QA Inspector report remains privacy safe", QaInspectorReportRemainsPrivacySafe),
    ("QA Inspector acceptance requires current verified visual evidence", QaInspectorAcceptanceRequiresCurrentVerifiedVisualEvidence),
    ("QA Inspector isolated capture preserves existing reviews read-only", QaInspectorIsolatedCapturePreservesExistingReviewsReadOnly),
    ("QA Inspector revalidates screenshot hashes before preview", QaInspectorRevalidatesScreenshotHashesBeforePreview),
    ("QA Inspector builds and pins fresh currentness validator output", QaInspectorBuildsAndPinsFreshCurrentnessValidatorOutput)
};

if (Environment.GetEnvironmentVariable("AIARENA_RUN_LIVE_INTERNET_SMOKE") == "1")
{
    tests.Add(("live bundled internet diagnostic", LiveBundledInternetDiagnostic));
}

var testFilter = Environment.GetEnvironmentVariable("AIARENA_TEST_FILTER");
if (!string.IsNullOrWhiteSpace(testFilter))
{
    tests.RemoveAll(test => !test.Name.Contains(testFilter, StringComparison.OrdinalIgnoreCase));
    if (tests.Count == 0)
    {
        Console.Error.WriteLine($"No tests matched AIARENA_TEST_FILTER='{testFilter}'.");
        return 2;
    }
}

var failures = 0;
foreach (var (name, test) in tests)
{
    try
    {
        test();
        Console.WriteLine($"PASS {name}");
    }
    catch (Exception ex)
    {
        failures++;
        Console.Error.WriteLine($"FAIL {name}: {ex.Message}");
        if (Environment.GetEnvironmentVariable("AIARENA_TEST_VERBOSE_FAILURES") == "1")
        {
            Console.Error.WriteLine(ex);
        }
    }
}

return failures == 0 ? 0 : 1;
    }
}
