using AIArena.Core.Models;
using AIArena.Core.Persistence;
using AIArena.Core.Providers;
using AIArena.Core.Services;
using AIArena.Wpf;
using AIArena.Wpf.Controls;
using AIArena.Wpf.Models;
using AIArena.Wpf.Services;
using System.Collections;
using System.Runtime.ExceptionServices;
using System.Resources;
using System.Text.Json;
using System.Threading;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;


internal static partial class Program
{
    private static int Main()
    {
var tests = new List<(string Name, Action Test)>
{
    ("saves and reloads visual generation settings", SaveReloadVisualGenerationSettings),
    ("agent workspace defaults on and persists its settings toggle", AgentWorkspaceDefaultsOnAndPersistsSettingsToggle),
    ("normalizes system theme and blank settings", NormalizeSystemThemeAndBlankSettings),
    ("voice narration settings and text cleanup stay stable", VoiceNarrationSettingsAndTextCleanupStayStable),
    ("app shutdown survives cleanup failures", AppShutdownSurvivesCleanupFailures),
    ("main window shutdown reclose is deferred", MainWindowShutdownRecloseIsDeferred),
    ("voice narration dispose wins delayed start", VoiceNarrationDisposeWinsDelayedStart),
    ("voice narration disposal drains an in-flight start", VoiceNarrationDisposalDrainsInFlightStart),
    ("voice narration isolates speaking changed failures", VoiceNarrationIsolatesSpeakingChangedFailures),
    ("overwrites read-only settings file", OverwriteReadOnlySettingsFile),
    ("json stores ignore stale temp files", JsonStoresIgnoreStaleTempFiles),
    ("backs up corrupt settings file", BackupCorruptSettingsFile),
    ("transient settings read failures preserve the file", TransientSettingsReadFailuresPreserveFile),
    ("backs up corrupt scenario template file", BackupCorruptScenarioTemplateFile),
    ("overwrites read-only scenario template file", OverwriteReadOnlyScenarioTemplateFile),
    ("scenario template load skips null records", ScenarioTemplateLoadSkipsNullRecords),
    ("scenario template restores dynamic roster", ScenarioTemplateRestoresDynamicRoster),
    ("provider reachability clamps probe timeout", ProviderReachabilityClampsProbeTimeout),
    ("provider reachability copies status metadata", ProviderReachabilityCopiesStatusMetadata),
    ("provider reachability preserves API mode", ProviderReachabilityPreservesApiMode),
    ("provider reachability formats provider-specific offline hints", ProviderReachabilityFormatsProviderSpecificOfflineHints),
    ("provider reachability preserves completion failure during refresh", ProviderReachabilityPreservesCompletionFailureDuringRefresh),
    ("provider reachability merges status after concurrent saves", ProviderReachabilityMergesStatusAfterConcurrentSaves),
    ("provider reachability rejects stale status after identity changes", ProviderReachabilityRejectsStaleStatusAfterIdentityChanges),
    ("provider configuration control applies atomic secret-safe patches", ProviderConfigurationControlAppliesAtomicSecretSafePatches),
    ("provider runtime rejects stale probe persistence", ProviderRuntimeRejectsStaleProbePersistence),
    ("provider runtime treats timeout changes as stale probe identity", ProviderRuntimeTreatsTimeoutChangesAsStaleProbeIdentity),
    ("provider runtime caps and redacts model catalogs", ProviderRuntimeCapsAndRedactsModelCatalogs),
    ("provider secret protection rewraps ambiguous legacy prefixes", ProviderSecretProtectionRewrapsAmbiguousLegacyPrefixes),
    ("NVIDIA telemetry probe cache bounds process launches", NvidiaTelemetryProbeCacheBoundsProcessLaunches),
    ("provider settings reset stale readiness on identity changes", ProviderSettingsResetStaleReadinessOnIdentityChanges),
    ("provider routing keeps current native options", ProviderRoutingKeepsCurrentNativeOptions),
    ("auto configure keeps low VRAM to one model", AutoConfigureLowVramSingleModel),
    ("auto configure spreads high VRAM model variety", AutoConfigureHighVramVariety),
    ("auto configure prefers useful multi GPU fit", AutoConfigurePrefersUsefulMultiGpuFit),
    ("lm studio catalog parses native model metadata", LmStudioCatalogParsesNativeModelMetadata),
    ("ollama catalog parses native model metadata", OllamaCatalogParsesNativeModelMetadata),
    ("lm studio catalog handles invalid native URL", LmStudioCatalogHandlesInvalidNativeUrl),
    ("lm studio catalog sends bearer token", LmStudioCatalogSendsBearerToken),
    ("lm studio provider surfaces nested native errors", LmStudioProviderSurfacesNestedNativeErrors),
    ("lm studio model download starts native job", LmStudioModelDownloadStartsNativeJob),
    ("lm studio model download checks status", LmStudioModelDownloadChecksStatus),
    ("ollama model pull starts native request", OllamaModelPullStartsNativeRequest),
    ("native provider operations propagate caller cancellation", NativeProviderOperationsPropagateCallerCancellation),
    ("provider reachability propagates caller cancellation", ProviderReachabilityPropagatesCallerCancellation),
    ("model preload sends bearer token", ModelPreloadSendsBearerToken),
    ("model preload caps requested context to native max", ModelPreloadCapsRequestedContextToNativeMax),
    ("model preload reloads low-context native instance", ModelPreloadReloadsLowContextNativeInstance),
    ("model preload reloads unknown-context native instance", ModelPreloadReloadsUnknownContextNativeInstance),
    ("model preload fails when loaded instance ids are missing", ModelPreloadFailsWhenLoadedInstanceIdsAreMissing),
    ("model unload sends bearer token", ModelUnloadSendsBearerToken),
    ("model preload uses Ollama keep alive", ModelPreloadUsesOllamaKeepAlive),
    ("model unload uses Ollama keep alive zero", ModelUnloadUsesOllamaKeepAliveZero),
    ("model preload handles invalid Ollama URL", ModelPreloadHandlesInvalidOllamaUrl),
    ("auto configure uses lm studio native metadata", AutoConfigureUsesLmStudioNativeMetadata),
    ("auto configure native mode uses native catalog first", AutoConfigureNativeModeUsesNativeCatalogFirst),
    ("auto configure ollama native ignores lm studio default endpoint", AutoConfigureOllamaNativeIgnoresLmStudioDefaultEndpoint),
    ("auto configure detects lm studio native catalog on default endpoint", AutoConfigureDetectsLmStudioNativeCatalogOnDefaultEndpoint),
    ("auto configure native fallback uses compatible mode", AutoConfigureNativeFallbackUsesCompatibleMode),
    ("auto configure sends bearer token", AutoConfigureSendsBearerToken),
    ("role style catalog normalizes labels and chips", RoleStyleCatalogNormalizesLabelsAndChips),
    ("role style catalog formats voice adherence cues", RoleStyleCatalogFormatsVoiceAdherenceCues),
    ("agent memory coordinator normalizes notes", AgentMemoryCoordinatorNormalizesNotes),
    ("agent board coordinator formats statuses", AgentBoardCoordinatorFormatsStatuses),
    ("agent board coordinator disables mode buttons while busy", AgentBoardCoordinatorDisablesModeButtonsWhileBusy),
    ("agent runbook persists stable workflow and recovers interruptions", AgentRunbookPersistsStableWorkflowAndRecoversInterruptions),
    ("agent workspace empty state stays compact", AgentWorkspaceEmptyStateStaysCompact),
    ("agent workspace command preview gates execution", AgentWorkspaceCommandPreviewGatesExecution),
    ("agent workspace command runner captures terminal output", AgentWorkspaceCommandRunnerCapturesTerminalOutput),
    ("agent workspace command rejects invalid timeouts", AgentWorkspaceCommandRejectsInvalidTimeouts),
    ("agent workspace clipboard helper handles busy clipboard", AgentWorkspaceClipboardHelperHandlesBusyClipboard),
    ("agent workspace file receipt scan is bounded", AgentWorkspaceFileReceiptScanIsBounded),
    ("agent workspace profile directory scan is bounded", AgentWorkspaceProfileDirectoryScanIsBounded),
    ("agent workspace profile skips oversized package json", AgentWorkspaceProfileSkipsOversizedPackageJson),
    ("agent workspace generated commands reject shell metacharacters", AgentWorkspaceGeneratedCommandsRejectShellMetacharacters),
    ("agent workspace bounded readers and candidates stop at limits", AgentWorkspaceBoundedReadersAndCandidatesStopAtLimits),
    ("agent workspace stages builder command proposals", AgentWorkspaceStagesBuilderCommandProposals),
    ("agent workspace blocks command approval during chat", AgentWorkspaceBlocksCommandApprovalDuringChat),
    ("agent workspace restores chat after restart", AgentWorkspaceRestoresChatAfterRestart),
    ("operator turn coordinator disables input during busy work", OperatorTurnCoordinatorDisablesInputDuringBusyWork),
    ("operator turn coordinator suggests interventions", OperatorTurnCoordinatorSuggestsInterventions),
    ("transcript action coordinator exposes automation names", TranscriptActionCoordinatorExposesAutomationNames),
    ("transcript export coordinator previews scope", TranscriptExportCoordinatorPreviewsScope),
    ("shell file export replaces read-only targets", ShellFileExportReplacesReadOnlyTargets),
    ("shell process launcher reports failures", ShellProcessLauncherReportsFailures),
    ("agent performance coordinator aggregates native telemetry", AgentPerformanceCoordinatorAggregatesNativeTelemetry),
    ("metric sparkline control measures responsively", MetricSparklineControlMeasuresResponsively),
    ("agent world layout maps active chat state", AgentWorldLayoutMapsActiveChatState),
    ("agent world pulse summarizes live telemetry", AgentWorldPulseSummarizesLiveTelemetry),
    ("agent world cue ribbon summarizes live events", AgentWorldCueRibbonSummarizesLiveEvents),
    ("agent world collision solver separates crowded robots", AgentWorldCollisionSolverSeparatesCrowdedRobots),
    ("agent world minimap markers stay inside frame", AgentWorldMiniMapMarkersStayInsideFrame),
    ("agent world minimap tracks camera focus", AgentWorldMiniMapTracksCameraFocus),
    ("agent world minimap markers expose automation labels", AgentWorldMiniMapMarkersExposeAutomationLabels),
    ("agent world 3d control uses extended accent fallbacks", AgentWorld3DControlUsesExtendedAccentFallbacks),
    ("agent world inspector close button exposes automation name", AgentWorldInspectorCloseButtonExposesAutomationName),
    ("agent world 3d control renders snapshot", AgentWorld3DControlRendersSnapshot),
    ("agent world 3d control renders narrator identity cues", AgentWorld3DControlRendersNarratorIdentityCues),
    ("agent world respects reduced motion and reuses frame state", AgentWorldRespectsReducedMotionAndReusesFrameState),
    ("agent world skips rebuild for unchanged snapshots", AgentWorldSkipsRebuildForUnchangedSnapshots),
    ("agent world empty snapshot resets transient world state", AgentWorldEmptySnapshotResetsTransientWorldState),
    ("agent world follow camera tracks speaker changes until manual selection", AgentWorldFollowCameraTracksSpeakerChangesUntilManualSelection),
    ("agent world resets transient state on session change", AgentWorldResetsTransientStateOnSessionChange),
    ("agent world hud resizes for narrow panes", AgentWorldHudResizesForNarrowPanes),
    ("agent world header badge fits long speaker names", AgentWorldHeaderBadgeFitsLongSpeakerNames),
    ("agent world keyboard controls camera and inspector", AgentWorldKeyboardControlsCameraAndInspector),
    ("agent world overview restores follow pan offset", AgentWorldOverviewRestoresFollowPanOffset),
    ("agent world bubble placement stays visible at edges", AgentWorldBubblePlacementStaysVisibleAtEdges),
    ("agent world material cache is bounded without invalidating live geometry", AgentWorldMaterialCacheIsBoundedWithoutInvalidatingLiveGeometry),
    ("main window skips hidden world snapshot refresh", MainWindowSkipsHiddenWorldSnapshotRefresh),
    ("arena operation coordinator selects operation mode", ArenaOperationCoordinatorSelectsOperationMode),
    ("scenario workflow separates replay and copy actions during auto chat", ScenarioWorkflowSeparatesReplayAndCopyDuringAutoChat),
    ("scenario workflow clipboard helper handles busy clipboard", ScenarioWorkflowClipboardHelperHandlesBusyClipboard),
    ("scenario workflow preserves generation history selection", ScenarioWorkflowPreservesGenerationHistorySelection),
    ("match setup coordinator plans rivalry matrix safely", MatchSetupCoordinatorPlansRivalryMatrixSafely),
    ("saved state workflow ignores stale checkpoint refresh", SavedStateWorkflowIgnoresStaleCheckpointRefresh),
    ("transcript adjunct helpers format labels", TranscriptAdjunctHelpersFormatLabels),
    ("diagnostics wait for the first scored turn", DiagnosticsWaitForFirstScoredTurn),
    ("transcript battle review summarizes match", TranscriptBattleReviewSummarizesMatch),
    ("transcript run trace summarizes spans", TranscriptRunTraceSummarizesSpans),
    ("transcript card renderer labels internet cards", TranscriptCardRendererLabelsInternetCards),
    ("transcript card renderer hides internet metadata by default", TranscriptCardRendererHidesInternetMetadataByDefault),
    ("transcript card renderer shows source globe on sourced turns", TranscriptCardRendererShowsSourceGlobeOnSourcedTurns),
    ("transcript card renderer progressively discloses message actions", TranscriptCardRendererProgressivelyDisclosesMessageActions),
    ("transcript mutation coordinator formats statuses", TranscriptMutationCoordinatorFormatsStatuses),
    ("arena run coordinator formats statuses", ArenaRunCoordinatorFormatsStatuses),
    ("arena run coordinator drains auto chat on stop", ArenaRunCoordinatorDrainsAutoChatOnStop),
    ("arena run coordinator survives provider and cancellation failures", ArenaRunCoordinatorSurvivesProviderAndCancellationFailures),
    ("operator draft receipts summarize routes", OperatorDraftReceiptsSummarizeRoutes),
    ("arena session mutation coordinator normalizes settings", ArenaSessionMutationCoordinatorNormalizesSettings),
    ("session overview coordinator formats summaries", SessionOverviewCoordinatorFormatsSummaries),
    ("shell ui helpers blend brushes", ShellUiHelpersBlendBrushes),
    ("dialog chrome close button exposes automation name", DialogChromeCloseButtonExposesAutomationName),
    ("custom dialogs preserve modal accessibility and responsive bounds", CustomDialogsPreserveModalAccessibilityAndResponsiveBounds),
    ("agent accent service normalizes colors", AgentAccentServiceNormalizesColors),
    ("window chrome service packs color refs", WindowChromeServicePacksColorRefs),
    ("app starts internet backend lazily", AppStartsInternetBackendLazily),
    ("searxng supervisor plans bundled launch", SearxngSupervisorPlansBundledLaunch),
    ("searxng supervisor cleans canceled startup", SearxngSupervisorCleansCanceledStartup),
    ("searxng supervisor stop is a startup barrier", SearxngSupervisorStopIsStartupBarrier),
    ("searxng supervisor disposal cleans delayed start", SearxngSupervisorDisposalCleansDelayedStart),
    ("searxng supervisor replaces an unhealthy owned child", SearxngSupervisorReplacesUnhealthyOwnedChild),
    ("searxng supervisor rejects stale health after child exit", SearxngSupervisorRejectsStaleHealthAfterChildExit),
    ("searxng supervisor rejects stale initial health after owned exit", SearxngSupervisorRejectsStaleInitialHealthAfterOwnedExit),
    ("searxng supervisor initial health honors stop generation", SearxngSupervisorInitialHealthHonorsStopGeneration),
    ("searxng supervisor reports backend health", SearxngSupervisorReportsBackendHealth),
    ("internet diagnostics report real search metadata", InternetDiagnosticsReportSearchMetadata),
    ("internet diagnostics supersede older runs", InternetDiagnosticsSupersedeOlderRuns),
    ("internet diagnostics keep cancellation alive while superseded runs unwind", InternetDiagnosticsKeepCancellationAliveWhileSupersededRunsUnwind),
    ("internet diagnostics keep cancellation alive while disposed runs unwind", InternetDiagnosticsKeepCancellationAliveWhileDisposedRunsUnwind),
    ("internet diagnostics survive cancellation callback failures", InternetDiagnosticsSurviveCancellationCallbackFailures),
    ("internet backend health keeps cancellation alive while superseded refreshes unwind", InternetBackendHealthKeepsCancellationAliveWhileSupersededRefreshesUnwind),
    ("internet workflow persists direct toggle and controls backend", InternetWorkflowStartsAndStopsBackendWithToggle),
    ("internet toggle persists session immediately", InternetTogglePersistsSessionImmediately),
    ("internet toggle persistence stays with originating session", InternetTogglePersistenceStaysWithOriginatingSession),
    ("internet diagnostics clean up temporary backend while off", InternetDiagnosticsCleanUpTemporaryBackendWhileOff),
    ("internet workflow formats backend health", InternetWorkflowFormatsBackendHealth),
    ("internet workflow formats actionable diagnostics", InternetWorkflowFormatsActionableDiagnostics),
    ("release scripts protect installer distributions", ReleaseScriptsProtectInstallerDistributions),
    ("app icon resource is packaged", AppIconResourceIsPackaged),
    ("user guide app icon image source loads", UserGuideAppIconImageSourceLoads),
    ("user guide header icon image source loads", UserGuideHeaderIconImageSourceLoads),
    ("user guide read handles missing files", UserGuideReadHandlesMissingFiles),
    ("user guide search matches unordered tokens", UserGuideSearchMatchesUnorderedTokens),
    ("user guide article header trims long titles", UserGuideArticleHeaderTrimsLongTitles),
    ("provider reachability coordinator formats popup state", ProviderReachabilityCoordinatorFormatsPopupState),
    ("provider reachability projects one coherent UI generation", ProviderReachabilityProjectsOneCoherentUiGeneration),
    ("truncate respects its limit and suffix", TruncateRespectsItsLimitAndSuffix),
    ("session picker hides empty sessions without losing reach", SessionPickerHidesEmptySessionsWithoutLosingReach),
    ("session token accounting reports totals and pressure", SessionTokenAccountingReportsTotalsAndPressure),
    ("cross session search attributes and caps hits", CrossSessionSearchAttributesAndCapsHits),
    ("idle polling cadence only when nothing is running", IdlePollingCadenceOnlyWhenNothingIsRunning),
    ("transcript row sync preserves unchanged tail", TranscriptRowSyncPreservesUnchangedTail),
    ("advertised shortcuts are handled", AdvertisedShortcutsAreHandled),
    ("shell state changes reach the control plane from both routes", ShellStateChangesReachTheControlPlaneFromBothRoutes),
    ("command palette ranks matches predictably", CommandPaletteRanksMatchesPredictably),
    ("empty and off states are not styled as failures", EmptyAndOffStatesAreNotStyledAsFailures),
    ("dependency index check ignores line endings", DependencyIndexCheckIgnoresLineEndings),
    ("every human drivable event has a shared publisher", EveryHumanDrivableEventHasASharedPublisher),
    ("control plane key parsing accepts what people write", ControlPlaneKeyParsingAcceptsWhatPeopleWrite),
    ("screenshots and modals do not misreport the app", ScreenshotsAndModalsDoNotMisreportTheApp),
    ("settings and match setup do not share the window", SettingsAndMatchSetupDoNotShareTheWindow),
    ("narrowing the window does not hide the rail for good", NarrowingTheWindowDoesNotHideTheRailForGood),
    ("crashes leave something behind", CrashesLeaveSomethingBehind),
    ("an unknown theme is refused rather than substituted", AnUnknownThemeIsRefusedRatherThanSubstituted),
    ("generation refuses unknown options instead of substituting", GenerationRefusesUnknownOptionsInsteadOfSubstituting),
    ("provider error text cannot be a whole web page", ProviderErrorTextCannotBeAWholeWebPage),
    ("rejected workspace paths are reported as failures", RejectedWorkspacePathsAreReportedAsFailures),
    ("empty arguments are not mistaken for missing ones", EmptyArgumentsAreNotMistakenForMissingOnes),
    ("status tones avoid agent identity accents", StatusTonesAvoidAgentIdentityAccents),
    ("shell navigation coordinator selects themes", ShellNavigationCoordinatorSelectsThemes),
    ("app settings coordinator selects provider focus", AppSettingsCoordinatorSelectsProviderFocus),
    ("coordinator render contracts cover smoke states", CoordinatorRenderContractsCoverSmokeStates),
    ("transcript list coordinator selects retryable turns", TranscriptListCoordinatorSelectsRetryableTurns),
    ("transcript empty state reflects readiness and filters", TranscriptEmptyStateReflectsReadinessAndFilters),
    ("transcript view coordinator normalizes view state", TranscriptViewCoordinatorNormalizesViewState),
    ("transcript view coordinator adapts dashboard widths", TranscriptViewCoordinatorAdaptsDashboardWidths),
    ("transcript search coordinator keeps close available when empty", TranscriptSearchCoordinatorKeepsCloseAvailableWhenEmpty),
    ("dispatcher debouncer coalesces and flushes work", DispatcherDebouncerCoalescesAndFlushesWork),
    ("transcript search coordinator debounces text refresh", TranscriptSearchCoordinatorDebouncesTextRefresh),
    ("transcript search coordinator debounces collaborate result rendering", TranscriptSearchCoordinatorDebouncesCollaborateResultRendering),
    ("transcript search coordinator keeps surface queries separate", TranscriptSearchCoordinatorKeepsSurfaceQueriesSeparate),
    ("transcript search coordinator exposes row automation", TranscriptSearchCoordinatorExposesRowAutomation),
    ("collaborate history keeps duplicate display titles", CollaborateHistoryKeepsDuplicateDisplayTitles),
    ("collaborate history filters empty exchanges before cap", CollaborateHistoryFiltersEmptyExchangesBeforeCap),
    ("collaborate history save preserves caller objects", CollaborateHistorySavePreservesCallerObjects),
    ("collaborate history load skips null records", CollaborateHistoryLoadSkipsNullRecords),
    ("transient collaborate history reads preserve the file", TransientCollaborateHistoryReadsPreserveFile),
    ("collaborate search finds saved chat content", CollaborateSearchFindsSavedChatContent),
    ("collaborate recent chat metadata summarizes runs", CollaborateRecentChatMetadataSummarizesRuns),
    ("collaborate recent compare summarizes run deltas", CollaborateRecentCompareSummarizesRunDeltas),
    ("collaborate recent filters organize saved runs", CollaborateRecentFiltersOrganizeSavedRuns),
    ("collaborate recent list summarizes saved runs", CollaborateRecentListSummarizesSavedRuns),
    ("collaborate recent actions fork and repeat chats", CollaborateRecentActionsForkAndRepeatChats),
    ("collaborate preflight accepts role-specific models", CollaboratePreflightAcceptsRoleSpecificModels),
    ("collaborate run plan summarizes model calls", CollaborateRunPlanSummarizesModelCalls),
    ("collaborate interruption exchanges remain persistable", CollaborateInterruptionExchangesRemainPersistable),
    ("collaborate memory notes persist with conversations", CollaborateMemoryNotesPersistWithConversations),
    ("collaborate prompt budget summarizes context", CollaboratePromptBudgetSummarizesContext),
    ("collaborate context receipt summarizes payload", CollaborateContextReceiptSummarizesPayload),
    ("collaborate table summaries skip markdown dividers", CollaborateTableSummariesSkipMarkdownDividers),
    ("collaborate empty state stays compact", CollaborateEmptyStateStaysCompact),
    ("collaborate prompt templates preserve drafts", CollaboratePromptTemplatesPreserveDrafts),
    ("collaborate trace follow-up prompt preserves drafts", CollaborateTraceFollowUpPromptPreservesDrafts),
    ("collaborate run review summarizes traces", CollaborateRunReviewSummarizesTraces),
    ("collaborate control review exposes saved trace", CollaborateControlReviewExposesSavedTrace),
    ("collaborate conversation export includes run review and trace", CollaborateConversationExportIncludesRunReviewAndTrace),
    ("collaborate clear syncs shell status", CollaborateClearSyncsShellStatus),
    ("collaborate team debate header summarizes trace", CollaborateTeamDebateHeaderSummarizesTrace),
    ("collaborate blank role completion falls back to shared model", CollaborateBlankRoleCompletionFallsBackToSharedModel),
    ("collaborate send preserves history save failures", CollaborateSendPreservesHistorySaveFailures),
    ("collaborate failed sends are saved in history", CollaborateFailedSendsAreSavedInHistory),
    ("snapshot view mapper preserves provider telemetry", SnapshotViewMapperPreservesProviderTelemetry),
    ("snapshot view mapper attaches latest internet sources to agents", SnapshotViewMapperAttachesLatestInternetSourcesToAgents),
    ("agent internet sources presenter formats copy text", AgentInternetSourcesPresenterFormatsCopyText),
    ("custom match summary coordinator normalizes card text", CustomMatchSummaryCoordinatorNormalizesCardText),
    ("scenario seed inspector coordinator formats metadata", ScenarioSeedInspectorCoordinatorFormatsMetadata),
    ("provider quick setup coordinator formats defaults", ProviderQuickSetupCoordinatorFormatsDefaults),
    ("main window combobox template uses theme resources", MainWindowComboBoxTemplateUsesThemeResources),
    ("main window collaborate prompt uses multiline alignment", MainWindowCollaboratePromptUsesMultilineAlignment),
    ("main window collaborate prompt assist buttons stay compact", MainWindowCollaboratePromptAssistButtonsStayCompact),
    ("main window agent section is top level", MainWindowAgentSectionIsTopLevel),
    ("shell command state maps contextual workspace commands", ShellCommandStateMapsContextualWorkspaceCommands),
    ("main window contextual command hosts and provider metrics stay wired", MainWindowContextualCommandHostsAndProviderMetricsStayWired),
    ("main window navigation transitions preserve context", MainWindowNavigationTransitionsPreserveContext),
    ("main window agent command rail exposes approval contract", MainWindowAgentCommandRailExposesApprovalContract),
    ("main window export button switches context", MainWindowExportButtonSwitchesContext),
    ("main window match setup controls expose automation", MainWindowMatchSetupControlsExposeAutomation),
    ("main window voice tts settings expose automation", MainWindowVoiceTtsSettingsExposeAutomation),
    ("main window internet settings use one direct toggle", MainWindowInternetSettingsUseOneDirectToggle),
    ("main window model provider uses progressive disclosure", MainWindowModelProviderUsesProgressiveDisclosure),
    ("settings search expands nested disclosures and restores state", SettingsSearchExpandsNestedDisclosuresAndRestoresState),
    ("main window match setup matrix has clear action", MainWindowMatchSetupMatrixHasClearAction),
    ("main window operator quick interventions expose automation", MainWindowOperatorQuickInterventionsExposeAutomation),
    ("main window operator turn text uses multiline scroll affordance", MainWindowOperatorTurnTextUsesMultilineScrollAffordance),
    ("main window transcript search popup sizes responsively", MainWindowTranscriptSearchPopupSizesResponsively),
    ("main window overlays preserve keyboard and accessibility contracts", MainWindowOverlaysPreserveKeyboardAndAccessibilityContracts),
    ("main window adaptive shell layout stays wired", MainWindowAdaptiveShellLayoutStaysWired),
    ("main window live agents viewport stays constrained", MainWindowLiveAgentsViewportStaysConstrained),
    ("main window empty export status releases toolbar space", MainWindowEmptyExportStatusReleasesToolbarSpace),
    ("main window right rail collapse preserves keyboard context", MainWindowRightRailCollapsePreservesKeyboardContext),
    ("main window right rail adapts without changing preferences", MainWindowRightRailAdaptsWithoutChangingPreferences),
    ("main window snapshot refresh skips unchanged session scans", MainWindowSnapshotRefreshSkipsUnchangedSessionScans),
    ("control plane parses commands and stable responses", ControlPlaneParsesCommandsAndStableResponses),
    ("control plane requires session token", ControlPlaneRequiresSessionToken),
    ("control plane rejects oversized requests", ControlPlaneRejectsOversizedRequests),
    ("control plane stop drains active clients", ControlPlaneStopDrainsActiveClients),
    ("control plane restarts after a drained stop", ControlPlaneRestartsAfterDrainedStop),
    ("control plane async transitions do not block pending drain", ControlPlaneAsyncTransitionsDoNotBlockPendingDrain),
    ("control plane stop cancels blocked event writes", ControlPlaneStopCancelsBlockedEventWrites),
    ("control plane main window awaits lifecycle transitions", ControlPlaneMainWindowAwaitsLifecycleTransitions),
    ("control plane event queue is capped", ControlPlaneEventQueueIsCapped),
    ("control plane event queue overflow drains safely", ControlPlaneEventQueueOverflowDrainsSafely),
    ("control plane defaults on and persists its settings toggle", ControlPlaneDefaultsOnAndPersistsSettingsToggle),
    ("control plane events format json lines", ControlPlaneEventsFormatJsonLines),
    ("control plane dispatcher invokes on STA dispatcher", ControlPlaneDispatcherInvokesOnStaDispatcher),
    ("control plane known command registry covers first surface", ControlPlaneKnownCommandRegistryCoversFirstSurface),
    ("control plane powershell client exposes typed verbs", ControlPlanePowerShellClientExposesTypedVerbs),
    ("screenshot control service resolves safe paths and preserves existing files", ScreenshotControlServiceResolvesSafePathsAndPreservesExistingFiles),
    ("app screenshot handler captures a real PNG and publishes its event", AppScreenshotHandlerCapturesRealPngAndPublishesEvent),
    ("provider control handler routes commands and publishes events", ProviderControlHandlerRoutesCommandsAndPublishesEvents),
    ("provider diagnostics cache rejects switched and edited fingerprints", ProviderDiagnosticsCacheRejectsSwitchedAndEditedFingerprints),
    ("control plane main window delegates provider commands", ControlPlaneMainWindowDelegatesProviderCommands),
    ("saved state control service creates selects and restores", SavedStateControlServiceCreatesSelectsAndRestores),
    ("session fork workflow branches and sanitizes receipts", SessionForkWorkflowBranchesAndSanitizesReceipts),
    ("session fork workflow returns stable failure codes", SessionForkWorkflowReturnsStableFailureCodes),
    ("session fork control handler and PowerShell helper route safely", SessionForkControlHandlerAndPowerShellHelperRouteSafely),
    ("shell overlay control service preserves navigation contracts", ShellOverlayControlServicePreservesNavigationContracts),
    ("match setup control handler validates roster changes", MatchSetupControlHandlerValidatesRosterChanges),
    ("match setup package codec round trips exact portable state", MatchSetupPackageCodecRoundTripsExactPortableState),
    ("match setup portability creates clean sessions and protects tokens", MatchSetupPortabilityCreatesCleanSessionsAndProtectsTokens),
    ("match setup control handler exports and imports portable packages", MatchSetupControlHandlerExportsAndImportsPortablePackages),
    ("agent roster control path persists bounded cast changes", AgentRosterControlPathPersistsBoundedCastChanges),
    ("rivalry matrix control service persists named patterns", RivalryMatrixControlServicePersistsNamedPatterns),
    ("app preference control service persists safe updates", AppPreferenceControlServicePersistsSafeUpdates),
    ("scenario generation control service generates and replays native history", ScenarioGenerationControlServiceGeneratesAndReplaysNativeHistory),
    ("control plane publishes required event vocabulary", ControlPlanePublishesRequiredEventVocabulary),
    ("control plane navigation closes settings for main views", ControlPlaneNavigationClosesSettingsForMainViews),
    ("control plane Match Setup open owns the visible overlay", ControlPlaneMatchSetupOpenOwnsVisibleOverlay),
    ("agent workspace profile refresh ignores stale results", AgentWorkspaceProfileRefreshIgnoresStaleResults),
    ("agent workspace profile refresh disposes safely", AgentWorkspaceProfileRefreshDisposesSafely)
};

if (Environment.GetEnvironmentVariable("AIARENA_RUN_LIVE_INTERNET_SMOKE") == "1")
{
    tests.Add(("live bundled internet diagnostic", LiveBundledInternetDiagnostic));
}

var testFilter = Environment.GetEnvironmentVariable("AIARENA_TEST_FILTER");
if (!string.IsNullOrWhiteSpace(testFilter))
{
    tests.RemoveAll(test => !test.Name.Contains(testFilter, StringComparison.OrdinalIgnoreCase));
    if (tests.Count == 0)
    {
        Console.Error.WriteLine($"No tests matched AIARENA_TEST_FILTER='{testFilter}'.");
        return 2;
    }
}

var failures = 0;
foreach (var (name, test) in tests)
{
    try
    {
        test();
        Console.WriteLine($"PASS {name}");
    }
    catch (Exception ex)
    {
        failures++;
        Console.Error.WriteLine($"FAIL {name}: {ex.Message}");
    }
}

return failures == 0 ? 0 : 1;
    }
}
